### ISSUE TITLE
Lambda Node.js 6.10 runtime is deprecated

### ISSUE THREAD

**Issue by mattsb42-aws** [aws-samples/busy-engineers-encryption-sdk#111]
We create some inline Lambdas in CloudFormation templates using the `nodejs6.10` runtime.
This runtime is deprecated and no longer supported for creating new Lambdas.

We need to update this to a [supported runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). I would personally prefer `nodejs10.x` in order to avoid having to do this again for as long as possible.

**Comment by ksamreen** [comment]
Hi @mattsb42-aws - So I looked into this and it looks like Nodejs8.10 is the version supported for Amazon Linux (which is what we use in this example). Nodejs10.x is supported for Amazon Linux 2. I am not sure if we want to migrate over to using an Amazon Linux 2 image. Thoughts?

**Comment by ksamreen** [comment]
Hi @mattsb42-aws - I gave it a shot with the later version of node (node 10.15) and I am getting this error:

11:10:06 UTC-0700 | CREATE_FAILED | AWS::Lambda::Function | LogsConsoleRedirectLambdaFunc | ZipFile can only be used when Runtime is set to either of nodejs, nodejs4.3, nodejs6.10, nodejs8.10, python2.7, python3.6, python3.7.
-- | -- | -- | -- | --

**Comment by mattsb42-aws** [comment]
Today a customer reported that this is now failing. It looks like Lambda has dropped support for launching new nodejs8.10 functions.

**Comment by mattsb42-aws** [comment]
All branches should now be updated to use `nodejs12.x`, so we should be ok on this front for a while.

Thanks @minggong94 !
