### ISSUE TITLE
python destroy intermittently fails to empty bucket before deletion

### ISSUE THREAD

**Issue by mattsb42-aws** [aws-samples/busy-engineers-encryption-sdk#112]
`tox -e destroy` in the `exercise-1-start-python` branch fails to empty the bucket, resulting in a stack deletion failure.

It looks like what is happening is that old object *versions* are not being deleted.

Needed: Verify behavior in each other Python branch.

- [x] `exercise-1-start-python` : fails
- [x] `exercise-2-start-python` : works
- [x] `exercise-3-start-python` : works
- [x] `exercise-4-start-python` : works
- [x] `exercise-4-finished-python` : works

**Comment by mattsb42-aws** [comment]
Looks like this is only present in `exercise-1-start-python`.

**Comment by ksamreen** [comment]
I just retried the tax -e destroy, and I am not getting a stack deletion failure. Just thought I should let you know!

**Comment by mattsb42-aws** [comment]
@ksamreen which branch are you on?

**Comment by ksamreen** [comment]
on the exercise-1-start-python branch

**Comment by mattsb42-aws** [comment]
Hmmm, I re-ran my testing and it failed on the first destroy then succeeded on the second destroy. I suspect this is eventual consistency on the deletes tripping us up. Might need to wait for a bit after clearing the bucket.
